
# Required: A short name for the action package
name: Excel

# Required: A description of what's in the action package.
description: Operate on local Excel files directly.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/Sema4AI/prebuilt-actions/blob/main/excel/README.md

dependencies:
  conda-forge:
    - python=3.10.14
    - uv=0.1.41
  pypi:
    - sema4ai-actions=0.5.0
    - robocorp-excel=0.4.4

packaging:
  # This section is optional.
  # By default all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
