# Required: A short name for the action package
name: Snowflake Cortex Analyst

# Required: A description of what's in the action package.
description: Snowflake Cortex reliably answers business questions based on your structured data in Snowflake.

# Package version number, recommend using semver.org
version: 2.0.4

spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.14
    - uv=0.8.17
  pypi:
    - sema4ai-actions=1.6.1
    - pandas=2.3.3
    #- sema4ai-data=1.2.0 
    - sema4ai_data-1.2.101-py3-none-any.whl
    - snowflake=1.8.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
