# Required: A short name for the action package
name: Email actions

# Required: A description of what's in the action package.
description: Base actions needed to send emails using Sema4.ai service.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/Sema4AI/prebuilt-actions/blob/main/email/README.md

dependencies:
  conda-forge:
    - python=3.10.12
    - uv=0.1.38
    - python-dotenv=1.0.1
  pypi:
    - sema4ai-actions=0.3.1
    - pydantic=2.7.1

packaging:
  exclude:
    - "*.pyc" # Excludes .pyc files anywhere
    - ".vscode/**" # Excludes the `.vscode` directory in the current dir
    - "./devdata/**" # Excludes the `devdata` directory in the current dir
    - ".*" # Excludes all hidden files