# Required: A short name for the action package
name: Wayback Machine

# Required: A description of what's in the action package.
description: Uses the Wayback Machine to detect changes to websites.

# Package version number, recommend using semver.org
version: 1.0.1

dependencies:
  conda-forge:
    - python=3.10.16
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.3.0
    - pytz=2024.1
    - waybackpy=3.0.6

packaging:
  # This section is optional.
  # By default all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
