# Required: A short name for the action package
name: Microsoft OneDrive

# Required: A description of what's in the action package.
description: Work with Microsoft OneDrive.

# Package version number, recommend using semver.org
version: 0.0.1

dependencies:
  conda-forge:
    - python=3.10.14
    - python-dotenv=1.0.1
    - uv=0.4.16
  pypi:
    - sema4ai-actions=0.10.0
    - requests=2.32.3
    - pydantic=2.9.2
    - msal=1.31.0 

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
