# Required: A short name for the action package
name: Snowflake Cortex Search

# Required: A description of what's in the action package.
description: Cortex Search is a retrieval engine that provides agent the context it needs based on your latest data.

# Package version number, recommend using semver.org
version: 1.0.6

spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.11
    - sema4ai-data=1.0.5
    - snowflake-connector-python[pandas]=3.15.0
    - pandas=2.2.3
    - snowflake=1.5.1
    - pyjwt=2.10.1

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
    - ./**/*.log
