
# Required: A short name for the action package
name: Google Drive

# Required: A description of what's in the action package.
description: Atomic actions operating with Google Drive.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/sema4ai/prebuilt-actions/google-drive/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - pip=23.2.1
  - robocorp-truststore=0.8.0
  - python-dotenv=1.0.1
  pypi:
  - robocorp=2.0.2
  - sema4ai-actions=0.4.0
  - google-api-python-client=2.127.0
  - google-auth-oauthlib=1.2.0
  - google-auth-httplib2=0.2.0
  - pydantic=2.6.4
  - pandas=2.2.2
  - openpyxl=3.1.2
