# Required: A short name for the action package
name: Microsoft Mail

# Required: A description of what's in the action package.
description: Actions for Microsoft 365 Outlook emails.

# Package version number, recommend using semver.org
version: 1.3.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.10.16
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.3.6
    - pydantic=2.10.4
    - requests=2.32.3
    - msal=1.31.1

external-endpoints:
  - name: "Microsoft Graph API"
    description: "Access email data from Microsoft Graph API"
    additional-info-link: "https://learn.microsoft.com/en-us/graph/use-the-api"
    rules:
      - host: "graph.microsoft.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
