# Required: A short name for the action package
name: Robocorp

# Required: A description of what's in the action package.
description: Manage Robocorp automations from agents

# Package version number, recommend using semver.org
version: 1.0.0

spec-version: v2

dependencies:
  conda-forge:
  - python=3.11.11
  - uv=0.6.11
  - python-dotenv=1.1.0
  pypi:
  - sema4ai-actions=1.3.6
  - requests=2.32.3
  - pydantic=2.10.6

external-endpoints:
  - name: "Robocorp Control Room"
    description: "Access Robocorp Control Room API to manage automations"
    additional-info-link: "https://robocorp.com/api"
    rules:
      - host: "cloud.robocorp.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_store/**
  - ./**/*.pyc
  - ./**/*.zip
  - ./**/.env
 