# Required: A short name for the action package
name: Serper

# Required: A description of what's in the action package.
description: Interact with the Serper API to perform Google searches.

# Required: The version of the action package.
version: 0.0.1

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
  - python=3.10.16
  - python-dotenv=1.0.1
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.5
  - pydantic=2.10.6

packaging:
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
