# Required: A short name for the action package
name: XPDF

# Required: A description of what's in the action package
description: Reading and finding text- and image-based PDFs.

# Package version number, recommend using semver.org
version: 1.0.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.10.16
    - uv=0.4.17
    - tesseract=5.5.0
    - pdf2image=1.17.0
    - poppler=25.02.0
  pypi:
    - sema4ai-actions=1.3.3
    - pydantic=2.10.4
    - pypdf=5.3.0
    - pytesseract=0.3.13
    - pillow=11.1.0
    - opencv-python-headless=4.11.0.86

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
