# Required: A short name for the action package
name: PDF

# Required: A description of what's in the action package
description: Reading and finding text- and image-based PDFs.

# Package version number, recommend using semver.org
version: 0.1.1

dependencies:
  conda-forge:
    - python=3.10.14
    - uv=0.4.17
    - tesseract=5.3.4
    - pdf2image=1.17.0
    - poppler=24.04.0
  pypi:
    - sema4ai-actions=1.0.1
    - pydantic=2.9.2
    - pypdf=4.2.0
    - pytesseract=0.3.10
    - pillow=10.3.0
    - opencv-python-headless=4.9.0.80

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
