# Required: A short name for the action package
name: AI Browsing

# Required: A description of what's in the action package
description: LLM assisted browsing

# Package version number, recommend using semver.org
version: 1.0.1

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.0
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.13
    - pydantic=2.11.7
    - browser-use=0.1.40
    - langchain-openai=0.3.1

post-install:
  - playwright install --with-deps chromium

external-endpoints:
  - name: "Access to the internet"
    description: "Accesses the internet to retrieve information."
    rules:
      - host: "0.0.0.0"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
