# Required: A short name for the action package
name: HubSpot

# Required: A description of what's in the action package
description: Atomic actions operating on resources in HubSpot.

# Package version number, recommend using semver.org
version: 1.1.0

dependencies:
  conda-forge:
    - python=3.10.14
    - python-dotenv=1.0.1
    - uv=0.2.6
  pypi:
    - sema4ai-actions=0.10.0
    - pydantic=2.7.4
    - hubspot-api-client=9.0.0
    - requests=2.32.3

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
