# Required: A short name for the action package
name: HubSpot

# Required: A description of what's in the action package
description: Search and manage all aspects of CRM objects, including companies, contacts, deals, and more.

# Package version number, recommend using semver.org
version: 1.2.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.10.16
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.3.5
    - pydantic=2.10.4
    - hubspot-api-client=11.1.0
    - requests=2.32.3

external-endpoints:
  - name: "HubSpot API"
    description: "Access HubSpot CRM API."
    additional-info-link: "https://developers.hubspot.com/docs/api/overview"
    rules:
      - host: "api.hubapi.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_Store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
