
# Required: A short name for the action package
name: Slack

# Required: A description of what's in the action package.
description: Action package description

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.12
  - uv=0.1.37
  - robocorp-truststore=0.8.0
  - python-dotenv=1.0.1
  pypi:
  - sema4ai-actions=0.3.1
  - slack_sdk=3.27.1
  - pydantic=2.7.1

packaging:
  # This section is optional.
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.idea/**