# Required: A short name for the action package
name: Browsing actions

# Required: A description of what's in the action package.
description: Base actions needed to get information from websites and interact with them.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/Sema4AI/prebuilt-actions/blob/main/browsing/README.md

dependencies:
  conda-forge:
    - python=3.10.12
    - uv=0.1.38
    - robocorp-truststore=0.8.0
    - python-dotenv=1.0.1
  pypi:
    - robocorp-browser=2.3.3
    - sema4ai-actions=0.3.1
    - pydantic=2.7.1
    - requests=2.31.0
    - duckduckgo-search=5.3.0

packaging:
  exclude:
    - "*.pyc" # Excludes .pyc files anywhere
    - ".vscode/**" # Excludes the `.vscode` directory in the current dir
    - "./devdata/**" # Excludes the `devdata` directory in the current dir
    - ".*" # Excludes all hidden files
