# Required: A short name for the action package
name: Browsing actions

# Required: A description of what's in the action package.
description: Base actions needed to get information from websites and interact with them.

# Required: The current version of this action package.
version: 0.0.1

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/prebuilt-actions

dependencies:
  conda-forge:
    - python=3.10.12
    - pip=23.2.1
    - robocorp-truststore=0.8.0
    - python-dotenv=1.0.1
  pypi:
    - robocorp-browser=2.3.3
    - robocorp-actions=0.2.0
    - pydantic=2.6.4
    - requests=2.31.0
    - duckduckgo-search=5.3.0