# Required: A short name for the action package
name: Agent Connector

# Required: A description of what's in the action package.
description: Actions to connect agents with each other

# Package version number, recommend using semver.org
version: 3.0.0

# The version of the `package.yaml` format.
spec-version: v2

# Required: A link to where the documentation on the package lives.
documentation: https://sema4.ai/

dependencies:
  conda-forge:
  - python=3.10.16
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.6
  - requests=2.32.3

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
