# Required: A short name for the action package
name: Snowflake Dev Utils

# Required: A description of what's in the action package.
description: Utilities and helpers for working with Snowflake in Sema4.ai Studio. See the grants, debug errors and more!

# Package version number, recommend using semver.org
version: 0.0.3

spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.14
    - uv=0.8.17
  pypi:
    - sema4ai-actions=1.6.1
    - sema4ai-data=1.2.1
    - pandas=2.3.3
    - snowflake=1.8.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
