# Required: A short name for the action package
name: Microsoft Teams

# Required: A description of what's in the action package.
description: Work with Microsoft Teams.

# Package version number, recommend using semver.org
version: 1.0.3

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.10.16
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.3.0
    - requests=2.32.3
    - pydantic[email]=2.10.4

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
