# Required: A short name for the action package
name: ServiceNow

# Required: A description of what's in the action package.
description: Actions interacting with a ServiceNow instance.

# Package version number, recommend using semver.org
version: 1.1.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
  - python=3.10.16
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.6
  - pydantic=2.10.4
  - sema4ai-http-helper=1.0.2
  - httpx=0.27.2

external-endpoints:
  - name: "ServiceNow API"
    description: "Access ServiceNow API."
    additional-info-link: "https://developer.servicenow.com/"
    rules:
      - host: "*.service-now.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_Store/**
  - ./**/*.pyc
  - ./**/*.zip
