# Required: A short name for the action package
name: Slack Saved Items

# Required: A description of what's in the action package.
description: Prebuilt actions that read and write to Slack channels.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/Sema4AI/prebuilt-actions/blob/main/slack/README.md

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.2.6
  - python-dotenv=1.0.1
  pypi:
  - sema4ai-actions=0.9.1
  - slack_sdk=3.27.2
  - pydantic=2.7.3
  - rapidfuzz=3.9.3
packaging:
  # This section is optional.
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.idea/**
