# Required: A short name for the action package
name: Slack

# Required: A description of what's in the action package
description: Actions for reading and writing from/to Slack channels.

# Package version number, recommend using semver.org
version: 2.0.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.3.0
    - pydantic=2.10.4
    - slack_sdk=3.34.0
    - rapidfuzz=3.11.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
