# Required: A short name for the action package
name: XSlack

# Required: A description of what's in the action package
description: Prebuilt actions for reading and writing from/to Slack channels.

# Package version number, recommend using semver.org
version: 1.0.1

dependencies:
  conda-forge:
    - python=3.10.14
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.0.1
    - pydantic=2.9.2
    - slack_sdk=3.29.0
    - rapidfuzz=3.9.3

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
