# Required: A short name for the action package
name: Perplexity

# Required: A description of what's in the action package.
description: Search the web with Perplexity

spec-version: v2

# Package version number, recommend using semver.org
version: 1.1.1

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.13

external-endpoints:
  - name: "Perplexity API"
    description: "Accesses the Perplexity API to retrieve information."
    additional-info-link: "https://docs.perplexity.ai/api-reference/chat-completions"
    rules:
      - host: "api.perplexity.ai"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
