spec-version: v2

# Required: A short name for the action package
name: Snowflake Data

# Required: A description of what's in the action package.
description: Actions for interacting with any data in Snowflake

# Package version number, recommend using semver.org
version: 0.0.5

dependencies:
  conda-forge:
    - python=3.12.12
    - uv=0.8.17
  pypi:
    - sema4ai-actions=1.6.4
    - sema4ai-data=1.2.1
    - pandas=2.3.3

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
    - ./**/__MACOSX
    - ./**/__pycache__
    - ./**/.git
    - ./node_modules/**
