# Required: A short name for the action package
name: Google Mail

# Required: A description of what's in the action package
description: Atomic actions operating with Google Mail (GMail) using OAuth2 authentication.

# Package version number, recommend using semver.org
version: 0.1.0

dependencies:
  conda-forge:
    - python=3.10.14
    - python-dotenv=1.0.1
    - uv=0.2.6
  pypi:
    - sema4ai-actions=0.9.2
    - pydantic=2.7.4
    - google-api-python-client=2.131.0
    - google-auth-oauthlib=1.2.0
    - google-auth-httplib2=0.2.0
    - markdown=3.6

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
