# Required: A short name for the action package
name: Snowflake Cortex

# Required: A description of what's in the action package.
description: Snowflake Cortex AI Actions

# Package version number, recommend using semver.org
version: 1.1.1

spec-version: v2

dependencies:
  conda-forge:
  - python=3.10.16
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.5
  - sema4ai-data=1.0.1
  - snowflake-connector-python[pandas]=3.13.2
  - pandas=2.2.3
  - tabulate=0.9.0
  - PyYAML=6.0.2
  - openpyxl=3.2.0b1
  - snowflake=1.0.5
  - snowflake-snowpark-python=1.28.0
  - pyjwt=2.10.1
  - streamlit=1.42.2

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_store/**
  - ./**/*.pyc
  - ./**/*.zip
