# Required: A short name for the action package
name: Serper

# Required: A description of what's in the action package.
description: Interact with the Serper API to perform Google searches.

# Required: The version of the action package.
version: 1.1.3

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.1
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.4.2
    - pydantic=2.11.9
    - urllib3=2.5.0

external-endpoints:
  - name: "Google Serper API"
    description: "Accesses the Google Serper API to retrieve information."
    additional-info-link: "https://serper.dev"
    rules:
      - host: "google.serper.dev"
        port: 443

packaging:
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
