name: Document Insights
description: Explore structured and unstructured documents with Sema4.ai
spec-version: v2
version: 1.1.4
dependencies:
  conda-forge:
  - python=3.11.12
  - uv=0.8.2
  pypi:
  - sema4ai-actions=1.6.4
  - pydantic=2.12.4
  - requests=2.32.5
  - reductoai=0.9.0
  - sema4ai-docint=0.12.0
dev-dependencies:
  conda-forge:
  - pytest=8.4.2
  - types-requests=2.32.4.20250913
  - ruff=0.14.3
  - mypy=1.18.2
dev-tasks:
  test: pytest tests
  lint: |
    ruff check src tests
    ruff format --check src tests
  typecheck: mypy --follow-imports=silent --strict src tests
  format: |
    ruff format src tests
packaging:
  exclude:
  - ./**/*.pyc
  - ./**/*.zip
  - ./**/.env
  - ./**/.git
  - ./**/__MACOSX
  - ./**/__pycache__
  - ./.DS_store/**
  - ./.env
  - ./.git/**
  - ./.gitignore
  - ./.mypy_cache/**
  - ./.pytest_cache/**
  - ./.ruff_cache/**
  - ./.venv/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./tests/**
  - ./venv/**
