# Required: A short name for the action package
name: Oil Gas Reports

# Required: A description of what's in the action package.
description: Actions for querying sales/customer data.

# Package version number, recommend using semver.org
version: 0.0.7

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.5
  - sema4ai-data=0.1.0
  - scipy=1.14.1
  - tabulate=0.9.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_store/**
  - ./**/*.pyc
  - ./**/*.zip