# Required: A short name for the action package
name: Snowflake Cortex Search

# Required: A description of what's in the action package.
description: Cortex Search is a retrieval engine that provides agent the context it needs based on your latest data.

# Package version number, recommend using semver.org
version: 1.1.0

spec-version: v2

dependencies:
  conda-forge:
  - python=3.10.16
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.6
  - sema4ai-data=1.0.2
  - snowflake-connector-python[pandas]=3.14.0
  - pandas=2.2.3
  - snowflake=1.1.0
  - pyjwt=2.10.1

external-endpoints:
  - name: "Snowflake API"
    description: "Access Snowflake API."
    additional-info-link: "https://docs.snowflake.com/en/guides"
    rules:
      - host: "*.snowflakecomputing.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
  - ./.git/**
  - ./.vscode/**
  - ./devdata/**
  - ./output/**
  - ./venv/**
  - ./.venv/**
  - ./.DS_Store/**
  - ./**/*.pyc
  - ./**/*.zip
