# Required: A short name for the action package
name: Web Search

# Required: A description of what's in the action package.
description: Interact with the Serper API to perform Google searches.

# Required: The version of the action package.
version: 1.0.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.0
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.11
    - pydantic=2.11.4

external-endpoints:
  - name: "Web Search API"
    description: "Accesses the web search through Sema4.ai demo API to retrieve information."
    additional-info-link: "https://sema4.ai/docs/team-edition"
    rules:
      - host: "demo-services.sema4ai.dev"
        port: 443

packaging:
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
