# Required: A short name for the action package
name: Google Search

# Required: A description of what's in the action package
description: Agent can make Google searches using a custom search engine (requires API key).

# Package version number, recommend using semver.org
version: 1.2.2

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.0
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.4.1
    - pydantic=2.11.2

external-endpoints:
  - name: "Google API"
    description: "Access Google API to retrieve informations."
    additional-info-link: "https://developers.google.com/explorer-help"
    rules:
      - host: "www.googleapis.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
