# Required: A short name for the action package
name: Example Oil Gas Reports

# Required: A description of what's in the action package.
description: Example action package demonstrating oil and gas production data analysis using PostgreSQL database queries, showcasing well production tracking, field analysis, and decline curve modeling.

# Package version number, recommend using semver.org
version: 1.0.1

spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.14
    - uv=0.8.17

  pypi:
    - sema4ai-actions=1.5.0
    - sema4ai-data=1.1.0
    - scipy=1.16.2
    - tabulate=0.9.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
