# Required: A short name for the action package
name: Zendesk

# Required: A description of what's in the action package.
description: Operate Zendesk tickets, assignments and comments with Agents.

# Package version number, recommend using semver.org
version: 1.5.1

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.0
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.13
    - pydantic=2.11.7

external-endpoints:
  - name: "Zendesk API"
    description: "Access Zendesk API."
    additional-info-link: "https://developer.zendesk.com/"
    rules:
      - host: "*.zendesk.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
