# Required: A short name for the action package
name: Zendesk

# Required: A description of what's in the action package.
description: Operate Zendesk tickets, assignments and comments with Agents.

# Package version number, recommend using semver.org
version: 1.1.0

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.3.0
    - pydantic=2.10.4
    - requests=2.32.3

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
