# Required: A short name for the action package
name: Google Sheets

# Required: A description of what's in the action package
description: Create and read spreadsheets. Add/update rows.

# Package version number, recommend using semver.org
version: 1.2.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.1
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.5.0
    - pydantic=2.11.7
    - gspread=6.2.1

external-endpoints:
  - name: "Google API"
    description: "Access Google API to retrieve informations."
    additional-info-link: "https://developers.google.com/explorer-help"
    rules:
      - host: "www.googleapis.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_Store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
