# Required: A short name for the action package
name: Google Calendar

# Required: A description of what's in the action package.
description: List calendars and search, create and update events in your Google Calendar.

# Package version number, recommend using semver.org
version: 1.0.4

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.3.0
    - pydantic=2.10.4
    - google-api-python-client=2.157.0
    - google-auth-oauthlib=1.2.1
    - google-auth-httplib2=0.2.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
