# Required: A short name for the action package
name: Email sending

# Required: A description of what's in the action package.
description: Base actions needed to send emails using Sema4.ai service.

# Package version number, recommend using semver.org
version: 0.9.0

dependencies:
  conda-forge:
    - python=3.10.14
    - python-dotenv=1.0.1
    - uv=0.2.4
  pypi:
    - sema4ai-actions=0.9.1
    - pydantic=2.7.1

packaging:
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
