# Required: A short name for the action package
name: Browsing

# Required: A description of what's in the action package
description: Get information from websites, and interact with them.

# Package version number, recommend using semver.org
version: 1.0.2

dependencies:
  conda-forge:
    - python=3.10.14
    - python-dotenv=1.0.1
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.0.1
    - pydantic=2.9.2
    - robocorp-browser=2.3.4
    - requests=2.32.3

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
