# Required: A short name for the action package
name: Wayback Machine

# Required: A description of what's in the action package.
description: Uses the Wayback Machine to detect changes to websites.

# Package version number, recommend using semver.org
version: 1.1.2

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.13
    - pytz=2024.2
    - waybackpy=3.0.6

external-endpoints:
  - name: "Access to the internet"
    description: "Accesses the internet to retrieve information."
    rules:
      - host: "0.0.0.0"
        port: 443

packaging:
  # This section is optional.
  # By default all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_Store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
