# Required: A short name for the action package
name: YouTube

# Required: A description of what's in the action package
description: Search for videos and extract various details from YouTube videos.

# Package version number, recommend using semver.org
version: 1.0.2

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
  - python=3.10.16
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.0
  - youtube_transcript_api=0.6.3
  - youtube_search=2.1.2

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
