# Required: A short name for the action package
name: YouTube

# Required: A description of what's in the action package
description: Search for videos and extract various details from YouTube videos.

# Package version number, recommend using semver.org
version: 1.1.1

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.8
    - youtube_transcript_api=0.6.3
    - youtube_search=2.1.2

external-endpoints:
  - name: "Youtube API"
    description: "Access Youtube API."
    additional-info-link: "https://developers.google.com/youtube/v3/docs"
    rules:
      - host: "www.googleapis.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_Store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
