# Required: A short name for the action package
name: Microsoft 365 Excel

# Required: A description of what's in the action package.
description: Actions for manipulating Microsoft 365 Excel files.

# Package version number, recommend using semver.org
version: 2.2.2

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.4.1
    - pydantic=2.11.7
    - XlsxWriter=3.2.0

external-endpoints:
  - name: "Microsoft Graph API"
    description: "Access Excel data from Microsoft Graph API"
    additional-info-link: "https://learn.microsoft.com/en-us/graph/use-the-api"
    rules:
      - host: "graph.microsoft.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
