# Required: A short name for the action package
name: ZMicrosoft 365 Excel

# Required: A description of what's in the action package.
description: Actions for manipulating Microsoft 365 Excel files.

# Package version number, recommend using semver.org
version: 2.0.0

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
  - python=3.10.16
  - uv=0.4.17
  pypi:
  - sema4ai-actions=1.3.0
  - pydantic=2.10.4
  - httpx=0.27.0
  - XlsxWriter=3.2.0

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
