# Required: A short name for the action package
name: Salesforce

# Required: A description of what's in the action package.
description: Doing basic queries on Salesforce data using the Salesforce API

# Package version number, recommend using semver.org
version: 1.2.1

# The version of the `package.yaml` format.
spec-version: v2

dependencies:
  conda-forge:
    - python=3.11.11
    - python-dotenv=1.1.0
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.11
    - pydantic=2.11.5

external-endpoints:
  - name: "Salesforce API"
    description: "Access Salesforce API."
    additional-info-link: "https://developer.salesforce.com/docs"
    rules:
      - host: "*.my.salesforce.com"
        port: 443

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_Store/**
    - ./**/*.pyc
    - ./**/*.zip
    - ./**/.env
