# Required: A short name for the action package
name: Excel

# Required: A description of what's in the action package
description: Operate on local Excel files directly.

# Package version number, recommend using semver.org
version: 2.0.0

dependencies:
  conda-forge:
    - python=3.10.14
    - uv=0.2.6
  pypi:
    - sema4ai-actions=0.9.2
    - pydantic=2.7.4
    - robocorp-excel=0.4.4

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
