# Required: A short name for the action package
name: Excel

# Required: A description of what's in the action package
description: Create, read and update sheets on local Excel files.

# Package version number, recommend using semver.org
version: 3.1.0

dependencies:
  conda-forge:
    - python=3.10.14
    - uv=0.4.17
  pypi:
    - sema4ai-actions=1.0.1
    - pydantic=2.9.2
    - robocorp-excel=0.4.5
    - pandas=2.2.3
    - sema4ai-crossplatform=0.1.2

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
