# Required: A short name for the action package
name: Search and Browse

# Required: A description of what's in the action package.
description: Base actions needed to get information from websites and interact with them.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/Sema4AI/prebuilt-actions/blob/main/search-and-browse/README.md

dependencies:
  conda-forge:
    - python=3.10.14
    - python-dotenv=1.0.1
    - uv=0.1.38
  pypi:
    - robocorp-browser=2.3.3
    - sema4ai-actions=0.6.0
    - pydantic=2.7.1
    - requests=2.31.0
    - duckduckgo-search=5.3.0

packaging:
  # This section is optional.
  # By default all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ".*" # Excludes all hidden files
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
