name: AI Actions S3 Publish

on:
  workflow_dispatch:
    # Enables manual triggering via GitHub Actions

jobs:
  run-rcc:
    runs-on: ubuntu-latest

    env:
      RCC_VERSION: v18.1.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download RCC executable
        run: |
          curl -L -o rcc "https://cdn.sema4.ai/rcc/releases/${{ env.RCC_VERSION }}/linux64/rcc"
          chmod +x rcc

      - name: Run RCC command
        run: |
          ./rcc run -t "Generate the whole gallery"
        working-directory: ./bin/publisher

      - name: Configure AWS credentials Dropbox bucket
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::710450854638:role/github-action-gallery
          
      - name: AWS S3 copies
        run: |
          echo "Initializing Gallery S3"
          S3_BASE_URL="s3://downloads.robocorp.com/gallery/actions"
          
          aws s3 cp manifest.json $S3_BASE_URL/manifest.json --cache-control max-age=120 --content-type "text/plain"

          # Copy all subdirectories with cache-control max-age=31536000
          for dir in */; do
            aws s3 cp "$dir" "$S3_BASE_URL/$dir" --recursive --cache-control max-age=31536000
          done
        working-directory: ./bin/publisher/result