name: Actions - Initialize S3 Gallery

on:
  workflow_dispatch:
    # Enables manual triggering via GitHub Actions

jobs:
  publish_packages:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required by AWS aws-actions/configure-aws-credentials
      contents: read
    env:
      RCC_VERSION: v18.1.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if manifest.json exists
        run: |
          if curl --head --silent --fail https://cdn.sema4.ai/gallery/actions/manifest.json; then
            echo "manifest.json exists. Stopping the workflow."
            exit 1
          else
            echo "manifest.json does not exist. Proceeding with the workflow."
          fi

      - name: Generate Gallery structure
        run: |
          cd bin
          curl -L -o rcc "https://cdn.sema4.ai/rcc/releases/${{ env.RCC_VERSION }}/linux64/rcc"
          chmod +x rcc
          ./rcc run -r publisher/robot.yaml -t "Build all packages"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::710450854638:role/github-action-gallery
          
      - name: AWS S3 copies
        run: |
          echo "Initializing Gallery S3"
          S3_BASE_URL="s3://downloads.robocorp.com/gallery/actions"
          cd bin/publisher/gallery
          ls -la

          # Copy the Action Package subdirectories
          # cache-control max-age=31536000, because these should be immutable
          for dir in */; do
            aws s3 cp "$dir" "$S3_BASE_URL/$dir" --recursive --cache-control max-age=31536000
          
            returnCode=$?

            # If the upload of any package fails, we want to break the workflow, as to not upload the manifest,
            # which should be the only source of truth. This is allow to re-run this workflow if some fails happened.
            if [ $returnCode -ne 0 ]; then
              echo "Upload of '$dir' package failed, exiting..."
              exit 1
            fi
          done

          # Copy the updated manifest
          aws s3 cp manifest.json $S3_BASE_URL/manifest.json --cache-control max-age=120 --content-type "text/plain"

      - name: Save Gallery artifact
        uses: actions/upload-artifact@v4
        with:
          name: gallery-artifact
          path: bin/publisher/gallery

  publish_environments:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write # required by AWS aws-actions/configure-aws-credentials
      contents: read
    strategy:
      fail-fast: false
      matrix:
        name:
          - ubuntu-py3.10
          - windows-py3.10
          - macos-py3.10
        include:
          - name: ubuntu-py3.10
            python: '3.10'
            os: ubuntu-latest
          - name: windows-py3.10
            python: '3.10'
            os: windows-latest
          - name: macos-py3.10
            os: macos-latest
            python: '3.10'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Gallery artifact
        uses: actions/download-artifact@v4
        with:
          name: gallery-artifact

      - name: Build Environments
        run: |
          cd bin
          curl -L -o rcc "https://cdn.sema4.ai/rcc/releases/${{ env.RCC_VERSION }}/linux64/rcc"
          chmod +x rcc
          ./rcc run -r publisher/robot.yaml -t "Build environments"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::710450854638:role/github-action-gallery

      - name: AWS S3 copies
        run: |
          S3_BASE_URL="s3://downloads.robocorp.com/holotree/sema4ai"
          cd bin/publisher/environments
          ls -la

          # Copy the environments
          # cache-control max-age=31536000, because these should be immutable
          for file in */; do
            aws s3 cp "$dir" "$S3_BASE_URL/$file" --cache-control max-age=31536000

            returnCode=$?

            if [ $returnCode -ne 0 ]; then
              echo "Uploading of '$file' environments failed, skipping..."
            fi
          done