name: AI Actions S3 Publish

on:
  workflow_dispatch:
    # Enables manual triggering via GitHub Actions

jobs:
  run-rcc:
    runs-on: ubuntu-latest

    env:
      RCC_VERSION: v18.1.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download RCC executable
        run: |
          curl -L -o rcc "https://cdn.sema4.ai/rcc/releases/${{ env.RCC_VERSION }}/linux64/rcc"
          chmod +x rcc

